[build]
  # Build command for Next.js on Netlify
  command = "npm run build"
  
  # Output directory for Next.js
  publish = ".next"
  
  # Node.js version and environment variables
  [build.environment]
    NODE_VERSION = "18"
    NODE_OPTIONS = "--max-old-space-size=4096"
    NEXT_TELEMETRY_DISABLED = "1"

# Enable Netlify's Next.js runtime
[functions]
  external_node_modules = ["sharp"]

# Configure redirects for Next.js routing
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"