[build]
  # Build command for Next.js with Netlify runtime
  command = "npm run build"
  
  # Output directory for Next.js with Netlify runtime
  publish = ".next"
  
  # Node.js version and environment variables
  [build.environment]
    NODE_VERSION = "18"
    NODE_OPTIONS = "--max-old-space-size=8192"
    NEXT_TELEMETRY_DISABLED = "1"

# Enable Next.js runtime on Netlify
[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Configure redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"