[build]
  # Build command for Next.js with Netlify runtime
  command = "npm run build"
  
  # Output directory for Next.js with Netlify runtime
  publish = ".next"
  
  # Node.js version and environment variables
  [build.environment]
    NODE_VERSION = "18"
    NODE_OPTIONS = "--max-old-space-size=8192"
    NEXT_TELEMETRY_DISABLED = "1"
    
    # Default environment variables for build (override in Netlify dashboard)
    STRIPE_SECRET_KEY = "sk_test_default"
    STRIPE_WEBHOOK_SECRET = "whsec_default"
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_default"
    KLAVIYO_API_KEY = "klaviyo_default_key"
    NEXT_PUBLIC_KLAVIYO_PUBLIC_KEY = "klaviyo_public_default"

# Netlify plugins for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for better performance and security
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"